### ISSUE TITLE
setup.sh

### ISSUE THREAD

**Issue by davetang** [DaehwanKimLab/hisat-genotype#10]
Hello,

there are carriage returns in `setup.sh`, which causes problems on Linux. I used `sed` to remove them.

    sed -i 's/\r$//' setup.sh

There is also a typo on line 46, which should be `submodule`

https://github.com/DaehwanKimLab/hisat-genotype/blob/32141b93b894d4a0be92a1becb18dabdcf70f446/setup.sh#L46

I could compile hisat2 after making these changes.

**Comment by chbe-helix** [comment]
Hi Dave,

Thanks for finding these issues! I'll update the tutorial/wiki and make these changes in the next version release in June/July.

Thanks,
Chris

**Comment by csmith-pact** [comment]
Can you recommend a stable version on git to use pending fixing these bugs?

**Comment by chbe-helix** [comment]
Hello,

The new version of HISATgenotype (1.3.1) has been released and has fixes for these issues. Please upgrade to the new version to apply these bug fixes. Thanks!

Thanks,
Chris
