### ISSUE TITLE
setup.sh version 20 May has a typo

### ISSUE THREAD

**Issue by nealamo** [DaehwanKimLab/hisat-genotype#14]
https://github.com/DaehwanKimLab/hisat-genotype/blob/32141b93b894d4a0be92a1becb18dabdcf70f446/setup.sh#L46

It says: git sumbodule init

I guess it should say:

git submodule init

**Comment by chbe-helix** [comment]
Hi nealamo,

Thank you for catching that typo! It will be fixed in the 1.3.1 release of HISATgenotype in July 2020.

Thanks,
Chris
