### ISSUE TITLE
No rule to make target 'hisat2-inspect-section'

### ISSUE THREAD

**Issue by masen0407** [DaehwanKimLab/hisat-genotype#17]
Hello,
when i use setup.sh to setup,it goes well at first ,but at end it report :
make: *** No rule to make target 'hisat2-inspect-section'.  Stop.

i work on Linux  3.10.0-957.5.1.el7.x86_64

**Comment by chbe-helix** [comment]
Hi Masen,

I'm working on fixing some of the errors in setup.sh. Please use the following code while in the hisatgenotype directory:
```
cd hisat2
git submodule init
git submodule update
make hisat2-align-s hisat2-build-s hisat2-inspect-s
```

This behavior will change once we get 1.3.1 released. Hope this helps!

Thanks,
Chris

**Comment by masen0407** [comment]
thank for you replay,
although i use the code you recommend,i still get a problem.
Traceback (most recent call last):
  File "/picb/humpopg-bigdata5/masen/bio/hisat-genotype/hisatgenotype", line 750, in <module>
    typing_process(args)
  File "/picb/humpopg-bigdata5/masen/bio/hisat-genotype/hisatgenotype", line 530, in typing_process
    assert fq_fname_base
AssertionError

this is my script:
hisatgenotype -x /dir/hisat2-genotype/genotype_genome --base hla --locus-list A -1 /dir/hisat2-genotype/ILMN_20181025/NA12892.hla.extracted.1.fq.gz -2 /dir/hisat2-genotype/ILMN_20181025/NA12892.hla.extracted.2.fq.gz
as you can see ,i use file in hisat2_20181025.tar.gz.

**Comment by chbe-helix** [comment]
Hi Masen,

There are a few things that are causing this:
1) if you're using genotype_genome reference we provide you don't need the -x option
2) version 1.3.0 does not have the option to use references in other directories at this time. If your genotype_genome file is not in your working directory you'll either get an error or hisatgenotype will try downloading the reference. Version 1.3.1 to be released soon has a new option that allows references in other directories.

Here is my suggestion based on your code:
```
ln -s /dir/hisat2-genotype/genotype_genome* ./
hisatgenotype --base hla --locus-list A -1 /dir/hisat2-genotype/ILMN_20181025/NA12892.hla.extracted.1.fq.gz -2 /dir/hisat2-genotype/ILMN_20181025/NA12892.hla.extracted.2.fq.gz
```

What we're doing is getting a soft link to the genotype_genome files in the working directory for hisatgenotype to find. This is a temporary patch that should help resolve that issue. in the next version of hisatgenotype this won't be necessary.

Hope this helps!
Thanks,
Chris

**Comment by chbe-helix** [comment]
Hi Masen,

The new version of HISATgenotype (1.3.1) has been released and has a new option to direct HISATgenotype to an index folder. You should now only have to download the index once and only at install if you desire. The manual will be updated with these changes soon. Thanks!

Thanks,
Chris
