### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by amomin-pact** [DaehwanKimLab/hisat-genotype#2]
Hi ,
   I am trying to test hisatgenotype with the test data however I get the following error. Are the inderlying script of hisatgenotype only compatible with Python 2 versions? If so which?

   Thanks
    Amin

hisat-genotype/hla-analysis$ hisatgenotype --base hla --locus-list A -1 ILMN/NA12892.extracted.1.fq.gz -2 ILMN/NA12892.extracted.2.fq.gz
  File "/home/ubuntu/projects/hisat-genotype/hisatgenotype", line 50
    print 'Exception in '+func.__name__
                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Exception in '+func.__name__)?

**Comment by chbe-helix** [comment]
Hi Amin,

Yes, HISATgenotype was built in Python 2.7. I'll be working on changing everything over to 3.7 in the coming months. Until then, please use python 2.7 with HISATgenotype.

Thanks,
Chris

**Comment by chbe-helix** [comment]
HISATgenotype is being converted to Python 3 this week. We are running some tests and updating the documentation. This issue will be closed at this time
