### ISSUE TITLE
Wrong variable name in hisatgenotype_typing_common.py

### ISSUE THREAD

**Issue by nikolasthuesen** [DaehwanKimLab/hisat-genotype#21]
https://github.com/DaehwanKimLab/hisat-genotype/blob/325f61cd17dd0d853acc9d36e48f6822ddb51380/hisatgenotype_modules/hisatgenotype_typing_common.py#L278

chr should be substituted with chrom if I am not mistaken. This definitely gave me an error before and changing it on my local script fixed the error.

**Comment by chbe-helix** [comment]
Thank you for noticing this. I will look into it and fix any issues it causes in the next release.

Thanks,
Chris

**Comment by chbe-helix** [comment]
Hello,

The new version of HISATgenotype (1.3.1) has been released and should have a fix for any error you have encountered from this syntax. Let me know if you have any other concerns or issues. Thanks!

Thanks,
Chris
