### ISSUE TITLE
Missing argument in genotyping_locus()

### ISSUE THREAD

**Issue by nikolasthuesen** [DaehwanKimLab/hisat-genotype#23]
https://github.com/DaehwanKimLab/hisat-genotype/blob/f348debae85ca89f5a975f9678515260661780cc/hisatgenotype#L634

args.ix_dir is missing in this list of arguments, leading to an error where debug_instr is not defined. debug_instr is defined, but since the arguments are provided in order and not as keyword arguments, the error message is "debug_instr" not provided.
Maybe this can be part of release 1.3.2 as well?

**Comment by chbe-helix** [comment]
Hi Nicolas,

I have made the correction. Thanks for your patience!

Thanks,
Chris

**Comment by nikolasthuesen** [comment]
Hi Chris

Thanks for the fast response and update.
