### ISSUE TITLE
Wrong variable name in hisatgenotype_typing_common.py

### ISSUE THREAD

**Issue by nikolasthuesen** [DaehwanKimLab/hisat-genotype#24]
https://github.com/DaehwanKimLab/hisat-genotype/blob/325f61cd17dd0d853acc9d36e48f6822ddb51380/hisatgenotype_modules/hisatgenotype_typing_common.py#L278

The issue, which I brought up earlier has returned. Maybe old code was reused, when going from 1.3.1 to 1.3.2?
https://github.com/DaehwanKimLab/hisat-genotype/issues/21

"chr should be substituted with chrom if I am not mistaken. This definitely gave me an error before and changing it on my local script fixed the error."

**Comment by chbe-helix** [comment]
Hi Nikolas,

Thanks for noticing this oversight! I'll push the change in a few hours. I will not iterate the version tag for this push but it will be on the most recent master branch. I'll let you know when I upload it. 

Thanks,
Chris

**Comment by nikolasthuesen** [comment]
Hi Chris
Thanks again. Nice work.
Nikolas

**Comment by chbe-helix** [comment]
Hi Nikolas,

It is done. Thank you for your patience!

Thanks,
Chris
