### ISSUE TITLE
Calling LOH for HLA using HISAT-genotype outputs

### ISSUE THREAD

**Issue by andreyto** [DaehwanKimLab/hisat-genotype#30]
Assuming I have tumor and normal WES samples, would it be relatively easy to estimate the allele-specific loss of heterozygosity for the HLA loci from the outputs of HISAT-genotype? I need an alternative for WES inputs to the LOHHLA program due to a restrictive non-commercial license of the latter.
Considering that HISAT-genotype provides the HLA allele frequency estimated without the ploidy assumptions (#28), would it be feasible to apply the formula \(1\) from [arcasHLA-genotype preprint](https://www.medrxiv.org/content/10.1101/2020.09.30.20204875v1) that estimates the purity- and ploidy-adjusted copy number in the tumor?

![image](https://user-images.githubusercontent.com/136912/98185254-3ffa3c80-1eda-11eb-8c09-d084849af1f4.png)

where &Psi; is tumor ploidy and &rho; is tumor purity estimated with a tool like Sequenza from the tumor/normal WES. This formula in turn was based on the one from the LOHHLA paper. They then call the LOH if the copy number for any allele is below 0.5.

**Comment by chbe-helix** [comment]
Hi Andreyto,

I would expect HISATgenotype to work for you to assess loss of heterogeneity for the reasons you mentioned. The only caveat is that we output the top 10 alleles called from the EM. If you need more I'd be happy to work with you to remove this restriction. Also, I wanted to make sure you are aware that we have the ability to simplify the calling of HISATgenotype to a set number of digits/fields in the HLA allele (ex A*01:01:01:01 -> A*01:01:01) an provide a new frequency estimate. Depending on your needs, this may be beneficial to you for your project. Let me know how I can help!

Thanks,
Chris

**Comment by andreyto** [comment]
Thanks, Chris! I think 10 alleles should be enough. The tail would only matter if the rank-abundance profile was flat, but in this case the estimated copy number would drop far below 0.5 anyway. Thanks for the point about aggregating into a low resolution allele assignments. We typically only care about the two-filed (four digit) resolution in our applications, so maybe this is the one that I need to use to define heterozygosity. Please feel free to close this issue. I can report later on how this went for us.
Andrey
