### ISSUE TITLE
Can I update the hla fasta and msf files from IPD-IMGT/HLA ftp?

### ISSUE THREAD

**Issue by smw1414** [DaehwanKimLab/hisat-genotype#34]
Hi hisat-genotype team, 

I am not sure weather you have modified the fasta , msf and dat files for the optimization of HLA typing. Can I update the hla fasta and msf files from IPD-IMGT/HLA ftp? Thanks.

**Comment by chbe-helix** [comment]
Hi smw,

We haven't modified the files from the IPD-IMGT site. You should be able to download and use the updated database. Keep in mind that some of their hosted databases have minor formatting inconsistencies that may interfere with the database building step. I have done some work to prevent this from breaking the build though I am not sure if all cases are handled yet. Let me know if you have any issues. Thanks!

Thanks,
Chris
