### ISSUE TITLE
Would hisat-genotype work with Panel sequencing ? 

### ISSUE THREAD

**Issue by Admera2020** [DaehwanKimLab/hisat-genotype#35]
Dear Author, 

Can the hisat-genotype be used for small gene panels or WES data for HLA typing ?

I was following the reference manual for the hisat-genotype, which has no mention regarding WES or small panel.  The tool utilizes  HISAT2 for graph representation and alignment. So if I understood the algorithm correctly from the recent paper [https://pubmed.ncbi.nlm.nih.gov/31375807/](url) , the first step is to create the linear graph, which will be robust for WGS but unsure how it will work with WES and especially with Panel sequencing. 

Best, 
Nihir

**Comment by chbe-helix** [comment]
Hi Nihir,

You should have no issues running hisat-genotype for panel or exome sequencing. You may only need to restrict the scope of the program to the regions of interest. For example, if you sequence the HLA-A, HLA-B, and HLA-DRB1 regions only you'd want to run hisat-genotype with `--base hla --locus-list A,B,DRB1` options. If you encounter any issues let me know.

Thanks,
Chris

**Comment by Admera2020** [comment]
Really appreciate your quick response and suggestions
