### ISSUE TITLE
can hisat-genotype genotype on whole human genome

### ISSUE THREAD

**Issue by masen0407** [DaehwanKimLab/hisat-genotype#37]
Hello,
can hisat-genotype  do genotype on other site beside Hla?
or maybe can hisat-genotype use graph to do genotype on whole human genome such like paragraph or VG?
And if it can ,how to do that?

**Comment by chbe-helix** [comment]
Hi Masen,

Stay tuned for HISAT-genotype2 where I am working on doing just what you mentioned. 

Thanks,
Chris
