### ISSUE TITLE
Fail to download genotype_genome_20180128.tar.gz

### ISSUE THREAD

**Issue by wshuai294** [DaehwanKimLab/hisat-genotype#39]
Hi Chris,

When I follow the instruction to download genotype_genome_20180128.tar.gz and ILMN.tar.gz, I failed to connect to the port.  Is there an alternative website to download them? Could you help me to figure it out?

Thanks.

Best,
WANG Shuai

**Comment by chbe-helix** [comment]
Hi Wang,

Did you try `wget ftp://ftp.ccb.jhu.edu/pub/infphilo/hisat-genotype/data/genotype_genome_20180128.tar.gz`?

Thanks,
Chris

**Comment by wshuai294** [comment]
Hi Chris,

Thank you for your quick reply. Now I can download it successfully.
I have tried this link before, however, maybe the network of my lab blocks the link. I can download it at home.

Thanks again.
WANG Shuai
