### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'graph_genome'

### ISSUE THREAD

**Issue by hsiaoyi0504** [DaehwanKimLab/hisat-genotype#4]
When I tried to run hisatgenotype_extract_reads.py in the latest release (1.1.3), I get the following error message:

```
File "/pkg/biology/HISAT-genotype/HISAT-genotype_v1.1.3/hisatgenotype_tools/hisatgenotype_extract_reads.py", line 49, in <module>
    if not args.graph_genome:
AttributeError: 'Namespace' object has no attribute 'graph_genome'
```

It seems to me that it is because graph_genome wasn't defined.

https://github.com/DaehwanKimLab/hisat-genotype/blob/7e72edc25ea6343e0139696c637973e889b68564/hisatgenotype_tools/hisatgenotype_extract_reads.py#L49

**Comment by chbe-helix** [comment]
Bug was resolved.

**Comment by hsiaoyi0504** [comment]
Fixed in https://github.com/DaehwanKimLab/hisat-genotype/commit/b64186a3a8f92e60f1a7a268190383986b67ad4d.
