### ISSUE TITLE
Allow use alternative location for HISAT2_fnames

### ISSUE THREAD

**Issue by hsiaoyi0504** [DaehwanKimLab/hisat-genotype#5]
https://github.com/DaehwanKimLab/hisat-genotype/blob/b64186a3a8f92e60f1a7a268190383986b67ad4d/hisatgenotype_modules/hisatgenotype_typing_common.py#L265-L272

Currently, the file location of hisat-genotype is pretty limited.
You need to put all the required files in a specific location.
Is it possible to update to make all those reference locations flexible and could be fed by command-line arguments?

**Comment by chbe-helix** [comment]
Hi hsiaoyi,

Thanks for the suggestion! I can add that into the next version of HISAT-genotype coming out soon. For now I suggest using:

```
ln -s TARGET LINK_NAME
```

To make a soft links to the files.

**Comment by chbe-helix** [comment]
Agreed! I plan to add support for this feature with the new release of HISAT-genotype based in Python 3

**Comment by hsiaoyi0504** [comment]
@chbe-helix May I know if this has been resolved by the new 1.3.0 version?

**Comment by chbe-helix** [comment]
Hi Hsiaoyi,

Short answer is unfortunately no I ran into some time constraints in the conversion. Version 1.3.1 coming in July 2020 will have this feature. Thank you for your continued patience in resolving this issue.

Thanks,
Chris

**Comment by chbe-helix** [comment]
Hi Hsiaoyi,

The new version of HISATgenotype (1.3.1) has been released and has a new option to direct HISATgenotype to an index folder. You should now only have to download the index once and only at install if you desire. The manual will be updated with these changes soon. Thanks!

Thanks,
Chris
