### ISSUE TITLE
indefinite stalling caused by exit(1) within process

### ISSUE THREAD

**Issue by gh-btsui** [DaehwanKimLab/hisat-genotype#56]
https://github.com/DaehwanKimLab/hisat-genotype/blob/76148238ca732c6df14b908954be827a09291aa1/hisatgenotype_modules/hisatgenotype_typing_core.py#L2167
In the following experiment with python processing, exit(1) will cause an indefinite stalling: 
`import multiprocessing
def s(i):
    exit(1)
with multiprocessing.Pool(1) as p:
    p.map(s,[0])`

**Comment by chbe-helix** [comment]
Hi btsui,

Thanks for the information! I'll make corrections to the code to avoid this error.

Thanks,
Chris

**Comment by gh-btsui** [comment]
Awesome thanks a lot! @chbe-helix
