### ISSUE TITLE
Bug in installation

### ISSUE THREAD

**Issue by twesigomwedavid** [DaehwanKimLab/hisat-genotype#6]
Hello, I tried following the manual for installing HISAT-genotype (https://daehwankimlab.github.io/hisat-genotype/manual) on a macOS (Python 2.7)

First, it says we should use `git checkout hisatgenotype_v1.1.2_beta `. However, it looks like hisatgenotype_v1.1.2_beta is no longer available. 

So I tried switching to hisatgenotype_v1.1.3. When I ran `make hisat2-align-s hisat2-build-s hisat2-inspect-s` I got the errors below:

`/usr/local/bin/g++ -O3 -m64 -msse2 -funroll-loops -g3 -DCOMPILER_OPTIONS="\"-O3 -m64 -msse2 -funroll-loops -g3 -DPOPCNT_CAPABILITY\"" -DPOPCNT_CAPABILITY \
	-fno-strict-aliasing -DHISAT2_VERSION="\"`cat VERSION`\"" -DBUILD_HOST="\"`hostname`\"" -DBUILD_TIME="\"`date`\"" -DCOMPILER_VERSION="\"`/usr/local/bin/g++ -v 2>&1 | tail -1`\"" -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE  -DBOWTIE_MM   -DBOWTIE2 -DNDEBUG -Wall \
	 -I third_party  \
	-o hisat2-align-s hisat2.cpp \
	ccnt_lut.cpp ref_read.cpp alphabet.cpp shmem.cpp edit.cpp gfm.cpp reference.cpp ds.cpp multikey_qsort.cpp limit.cpp random_source.cpp tinythread.cpp qual.cpp pat.cpp read_qseq.cpp aligner_seed_policy.cpp aligner_seed.cpp aligner_seed2.cpp aligner_sw.cpp aligner_sw_driver.cpp aligner_cache.cpp aligner_result.cpp ref_coord.cpp mask.cpp pe.cpp aln_sink.cpp dp_framer.cpp scoring.cpp presets.cpp unique.cpp simple_func.cpp random_util.cpp aligner_bt.cpp sse_util.cpp aligner_swsse.cpp outq.cpp aligner_swsse_loc_i16.cpp aligner_swsse_ee_i16.cpp aligner_swsse_loc_u8.cpp aligner_swsse_ee_u8.cpp aligner_driver.cpp splice_site.cpp  hisat2_main.cpp \
	-lpthread  
In file included from /usr/local/Cellar/gcc@6/6.5.0_2/include/c++/6.5.0/stdlib.h:36:0,
                 from hisat2.cpp:20:
/usr/local/Cellar/gcc@6/6.5.0_2/include/c++/6.5.0/cstdlib:75:25: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
                         ^
compilation terminated.
In file included from /usr/local/Cellar/gcc@6/6.5.0_2/lib/gcc/6/gcc/x86_64-apple-darwin18.5.0/6.5.0/include/stdint.h:9:0,
                 from ccnt_lut.cpp:20:
/usr/local/Cellar/gcc@6/6.5.0_2/lib/gcc/6/gcc/x86_64-apple-darwin18.5.0/6.5.0/include-fixed/stdint.h:27:32: fatal error: sys/_types/_int8_t.h: No such file or directory
 #include <sys/_types/_int8_t.h>
                                ^
compilation terminated.
In file included from /usr/local/Cellar/gcc@6/6.5.0_2/include/c++/6.5.0/bits/postypes.h:40:0,
                 from /usr/local/Cellar/gcc@6/6.5.0_2/include/c++/6.5.0/iosfwd:40,
                 from /usr/local/Cellar/gcc@6/6.5.0_2/include/c++/6.5.0/ios:38,
                 from /usr/local/Cellar/gcc@6/6.5.0_2/include/c++/6.5.0/ostream:38,
                 from /usr/local/Cellar/gcc@6/6.5.0_2/include/c++/6.5.0/iostream:39,
                 from ref_read.h:23,
                 from ref_read.cpp:20:
/usr/local/Cellar/gcc@6/6.5.0_2/include/c++/6.5.0/cwchar:44:19: fatal error: wchar.h: No such file or directory
 #include <wchar.h>
                   ^
compilation terminated.`

Also it looks like hisat2-align is not present in hisatgenotype_v1.1.3

What could I be doing wrong?

Thank you.

**Comment by chbe-helix** [comment]
Hi! 

Thank your for pointing out the type in my manual! You should certainly be on version 1.1.3 at this time. It looks like there is a package missing from your Mac when building HISAT2. I will consult with the HISAT2 developer to see if we can sort out the problem. Stay tuned and I'll update you as soon as we find something.

Thanks!

**Comment by parkchanhee** [comment]
@twesigomwedavid 
Could you compile again using xcode compiler(clang)?

**Comment by twesigomwedavid** [comment]
Thank you for the suggestion. I tried to use clang but I am getting this
error

(base) twesidave:hisat-genotype tdavid$ clang hisat2-align-s hisat2-build-s
hisat2-inspect-s

clang: error: no such file or directory: 'hisat2-align-s'

clang: error: no such file or directory: 'hisat2-build-s'

clang: error: no such file or directory: 'hisat2-inspect-s'

**Comment by parkchanhee** [comment]
@twesigomwedavid 
Try this command
`make CC=/usr/bin/gcc CPP=/usr/bin/g++`

**Comment by twesigomwedavid** [comment]
> @twesigomwedavid
> Try this command
> `make CC=/usr/bin/gcc CPP=/usr/bin/g++`

Ran without errors. I would like to do CYP2D6 typing to see whether everything is now working fine. I would like to ask more specific questions about CYP2D6 typing. May you direct me on the appropriate place to ask these. I tried sending an email to hisat2.genomics@gmail.com but haven't received any response.

**Comment by chbe-helix** [comment]
Glad to hear it is working! for CYP typing information please send an email to christopher@bennett-tech.dev. I'll happily help in anyway I can.
