### ISSUE TITLE
It seems that fastq file path cannot be parsed

### ISSUE THREAD

**Issue by gudeqing** [DaehwanKimLab/hisat-genotype#62]
hisatgenotype --base hla -1 /disk/biodatabase/testdata/dnaseq_somatic/GS82-171024C1_combined_R1.fastq.gz -2 /disk/biodatabase/testdata/dnaseq_somatic/GS82-171024C1_combined_R2.fastq.gz -p 3 --out-dir GS82 --pp 3
.//disk/biodatabase/testdata/dnaseq_somatic/GS82-171024C1_combined_R2.fastq.gz does not exist.
Traceback (most recent call last):
  File "/home/danny.gu/softwares/hisat-genotype-master/hisatgenotype", line 771, in <module>
    typing_process(args)
  File "/home/danny.gu/softwares/hisat-genotype-master/hisatgenotype", line 539, in typing_process
    assert fq_fname_base
AssertionError

**Comment by parkchanhee** [comment]
@gudeqing 
Could you try with the --in-dir option?

ex>
hisatgenotype --base hla -1 /disk/biodatabase/testdata/dnaseq_somatic/GS82-171024C1_combined_R1.fastq.gz -2 /disk/biodatabase/testdata/dnaseq_somatic/GS82-171024C1_combined_R2.fastq.gz -p 3 **--in-dir ""** --out-dir GS82 --pp 3

**Comment by gudeqing** [comment]
@parkchanhee 
Thank you, that solved my problem. Sorry that I did not notice this argument before.
