### ISSUE TITLE
Report the most likely alleles for a sample

### ISSUE THREAD

**Issue by mbosio85** [DaehwanKimLab/hisat-genotype#9]
Hello,

Is there a way to return  the most likely two alleles for a sample at 4 digit level e.g. A*02:01 / 
A*29:02 in the report? 
Is the option --best-alleles suitable for this ?

Thanks

Mattia

**Comment by chbe-helix** [comment]
Hi Mattia,

We have a script to help with that in the works. It is currently in hisatgenotype_scripts folder named hisatgenotype_conc_results-beta.py. This is a way to simplify the results into something that is easier to digest. I haven't added the ability to cut into the fields manually but will be adding that very soon. Let me know if this script can help you and solves your issue.

Thanks,
Chris

**Comment by mbosio85** [comment]
Thanks a lot Chris for the help,
The script you provided solved the issue.
I'll be checking for the updates you mention in a future.
Thanks again,
Mattia
